### ISSUE TITLE
possible authority / path collision

### ISSUE THREAD

**Issue by mikesamuel** [mjb2010/JS-URI-resolver-tester#1]
The [third RELATIVE82-88 test](
https://github.com/mjb2010/JS-URI-resolver-tester/blob/28f2a0f5dd0c1bb357de134e83e07c420dbd7acf/uri_tests.js#L278) reads

```js
	[".//g", "f:/a", "f://g"],
```

`.//g` seems to be a relative URI with a path of `.//g`

`f://g` seems an odd result since it seems we have moved part of the path into the authority component.  IIUC, `f://g` has a scheme of `f` and an authority of `g` and no path, query, or fragment.

`f:////g` seems a more appropriate output since it is the concatenation of

  1. `f:`, the scheme from the context
  2. `//` which specifies a blank authority and resolves any authority/path ambiguity
  3. `//g` which is the result of `remove_dot_segments(merge_paths("/a", ".//g"))` == `remove_dot_segments("/.//g")`

**Comment by mjb2010** [comment]
The expected result (`f://g`) is what the RFC 3986 algorithm demands, though, right?

If I recall correctly, it was a known issue when RFC 3986 was published that a few unusual types of relative ref & base URI combos would resolve in strange ways, and it was decided to just not worry about it. Presumably URI scheme authors would not encourage the use of such combinations, lest the results be less than ideal, as they are in this case.

@gklyne may have further comment since it's one of the tests he came up with.

**Comment by gklyne** [comment]
I agree its seems odd, but I also re-checked RFC3986 and I think it's what the algorithm calls for (cf. https://tools.ietf.org/html/rfc3986#section-5.2.4).  Looking back, I can see a case that resolving to f:/.//g might be more consistent, as the result of the RFC3986 algorithm can generate a syntactically invalid path from valid inputs (see https://tools.ietf.org/html/rfc3986#section-3.3, productions for path-absolute and segment-nz).

One might argue that the "remove_dot_segments" method should include extra conditions to deal with relative paths that start with ".//", "..//", "/.//" or "/..//".  But that's not what we currently have.

I dug out my original code with that test case, and can't find any provenance for it - it's similar to but not the same as any example in RFC3986.  I guess it's something that got added to clarify some edge case, but I neglected to note why at the time.

I've trawled the relevant URI WG list and found some discussion at https://lists.w3.org/Archives/Public/uri/2004Feb/0115.html

This particular example was raised at:

https://lists.w3.org/Archives/Public/uri/2004Nov/0052.html
https://lists.w3.org/Archives/Public/uri/2004Nov/0051.html

But I can't find any further discussion, so I guess I just left it to stand in my test suite.  I don't think anyone disagreed with it :-o.

**Comment by gklyne** [comment]
In distant hindsight, I think that part of the (historic) problem may be that all of the test cases created for RFC3986 were against a base URI that included an explicit authority component.

**Comment by mikesamuel** [comment]
@gklyne, Thanks for explaining.

IIUC, if I want to fail-stop absolutize (absolutize per the algo or fail to produce an output), that avoids this edge-case, I should fail when both the context and relative URL lacks an authority, and remove_dot_segments(merged_path) starts with "`//`".

> One might argue that the "remove_dot_segments" method ...<br>
> In distant hindsight, I think that part of the (historic) problem may be that all of the test cases created for RFC3986 were against a base URI that included an explicit authority component.

On the subject of explicitly documenting corner cases, I think remove_dot_segments was
mostly tested with absolute paths.

I had assumed that for all relative paths p0, p1: merge_paths(p0,p1) is relative.

[This SO question](https://stackoverflow.com/questions/46536991) outlines an input for which that is not the case.  If that analysis is correct, then the testcase

```js
     ["../bar", "file:foo/", ???],
```

might have a result of `file:/bar` instead of `file:bar`.

**Comment by gklyne** [comment]
@mikesamuel:

(1) I think so.

(2) "I had assumed that for all relative paths p0, p1: merge_paths(p0,p1) is relative"

Most of the time, but not always:  if the base path p1 is empty but comes from a URI with an authority component, the resulting path is absolute (https://tools.ietf.org/html/rfc3986#section-5.2.3).  Per the SO question, I think the result "file:/bar" is what the algorithm calls for, and I think it's consistent behaviour, though maybe not obvious.  Having a scheme name implies we are dealing with an absolute URI (ignoring here the discussion about "non-strict" mode).

Historically, prior to RFC3986, hierarchical and opaque paths were treated separately, and hierarchical paths would always start with a "/" (https://tools.ietf.org/html/rfc2396#section-3).  The relative reference resolution would apply only with hierarchical base paths ("Documents can only make use of relative URI when their base URI fits within the <hier_part> syntax." - https://tools.ietf.org/html/rfc2396#section-5).  RFC3986 removed this distinction to make reference resolution applicable without having to appeal to this distinction between opaque and hierarchical paths.

**Comment by mjb2010** [comment]
Thanks, guys. Closing this issue now that I have [added a comment to the code](https://github.com/mjb2010/JS-URI-resolver-tester/commit/5d2d64f404d28cec33aa05a4f241a97d14e8fcbf#diff-df522c84085e0e6dba34962fd68b4e51) to explain that the result is weird but expected.
